---

- name: wait for sso to be ready
  kubernetes.core.k8s_info:
    kind: Statefulset
    name: keycloak
    namespace: "{{ namespace_sso }}"
    wait_sleep: 10
    wait_timeout: 90


# https://github.com/Emergency-Response-Demo/install/issues/71
- name: "Define random value for variable siteadmin_role_id "
  set_fact:
    siteadmin_role_id: "{{ lookup('password', '/dev/null chars=ascii_letters length=32') }}"

- name: "wait for sso statefulset to be ready in {{ namespace_sso }}"
  shell: "{{ openshift_cli }} get statefulset/keycloak -o jsonpath='{.status.readyReplicas}' -n {{ namespace_sso }}"
  register: result
  until: result.stdout == '1'
  retries: 50
  delay: 10
  changed_when: False

- name: retrieve sso route
  shell: "{{ openshift_cli }} get route sso -o jsonpath='{.spec.host}' -n {{ namespace_sso }}"
  register: sso_route_cmd

- name: get sso admin credentials secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ namespace_sso }}"
    name: "{{ sso_admin_credentials_secret }}"
  register: sso_admin_credentials

- set_fact:
    sso_admin_user: "{{ sso_admin_credentials.resources[0].data.ADMIN_USERNAME  | b64decode }}"
    sso_admin_password: "{{ sso_admin_credentials.resources[0].data.ADMIN_PASSWORD | b64decode }}"
    sso_url: "https://{{ sso_route_cmd.stdout }}"
    sepsis_ui_route_url: "https://{{ sepsisdetection_ui_app_name }}-{{ project_name }}.{{ ocp_domain }}"
- debug:
    msg: "sso_admin_user = {{ sso_admin_user }}  ;  sso_admin_password = {{ sso_admin_password }}"


- name: get admin token
  uri:
    url: "{{ sso_url }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: "username={{ sso_admin_user }}&password={{ sso_admin_password }}&grant_type=password&client_id=admin-cli"
    status_code: 200
    validate_certs: no
  register: admin_token_result

- name: set admin token fact
  set_fact:
    admin_token: "{{ admin_token_result | json_query('json.access_token') }}"

- name: check if {{ sso_realm_id }} exists
  uri:
    url: "{{ sso_url }}/auth/admin/realms/{{ sso_realm_id }}"
    method: GET
    headers:
      Authorization: Bearer {{ admin_token }}
    status_code: 200,404
    validate_certs: no
  register: result
  changed_when: false


- name: create {{ sso_realm_id }} realm
  uri:
    url: "{{ sso_url }}/auth/admin/realms"
    method: POST
    headers:
      Authorization: Bearer {{ admin_token }}
      Content-Type: application/json
    body: "{{ lookup('template', 'templates/realm.json') }}"
    body_format: json
    status_code: 201
    validate_certs: no
  when: result.status == 404

- name: get rhsso realm certs
  uri:
    url: "{{ sso_url }}/auth/realms/{{ sso_realm_id }}/protocol/openid-connect/certs"
    validate_certs: false
    return_content: true
  register: sso_realm_certs
  changed_when: false

- name: extract sso realm cert modulus
  shell: echo "{{ sso_realm_certs.content|from_json|json_query(json_query) }}" | sed s/-/+/g | sed s/_/\\//g
  vars:
    json_query: keys[?kty=='RSA']|[0].n
  register: sso_realm_certs_modulus

- name: extract sso realm cert exponent
  shell: echo "{{ sso_realm_certs.content|from_json|json_query(json_query) }}"
  vars:
    json_query: keys[?kty=='RSA']|[0].e
  register: sso_realm_certs_exponent

- name: extract sso realm public key
  shell: |
    echo {{ sso_realm_certs_exponent.stdout }} | base64 -d > {{ work_dir }}/exponent.bin
    echo '02 03' | xxd -r -p > {{ work_dir }}/mid-header.bin
    echo 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA' | base64 -d > {{ work_dir }}/header.bin
    _m={{ sso_realm_certs_modulus.stdout }}
    _l={{ shell1 }}
    if [ $_l -eq 2 ]; then _s="$_m"'=='
    elif [ $_l -eq 3 ]; then _s="$_m"'='
    else _s="$_m" ; fi
    echo $_s | base64 -d > {{ work_dir }}/modulus.bin
    cat {{ work_dir }}/header.bin {{ work_dir }}/modulus.bin {{ work_dir }}/mid-header.bin {{ work_dir }}/exponent.bin > {{ work_dir }}/key.der
    openssl pkey -inform der -outform pem -pubin -in {{ work_dir }}/key.der -out {{ work_dir }}/key.pem
    echo $(cat {{ work_dir }}/key.pem | tr -d "\n" | sed 's/-----BEGIN PUBLIC KEY-----//' | sed 's/-----END PUBLIC KEY-----//' ) > {{ work_dir }}/sso_public_key.txt
    rm {{ work_dir }}/*.bin {{ work_dir }}/*.der {{ work_dir }}/*.pem
  vars:
    shell1: !unsafe "$((${#_m} % 4))"

- name: create client configmap
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace_sso }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ sso_config_configmap }}"
      data:
        AUTH_URL: "{{ sso_url }}/auth"
        KEYCLOAK: "true"
        PUBLIC_KEY: "{{ lookup('file', work_dir + '/sso_public_key.txt') }}"
        REALM: "{{ sso_realm_id }}"
        CLIENTID: "{{ sso_clientId }}"

