---

- name: delete route
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: route.openshift.io/v1
    kind: Route

- name: "delete service {{ application_name }}"
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: Service

- name: "delete DeploymentConfig {{ application_name }}"
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig

- name: delete imagestream in the {{ namespace }} project
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: ImageStream

- name: "delete configmap {{ application_configmap }}"
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: ConfigMap
