---

# create project

- name: create project {{ namespace }}
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/project.yml') | from_yaml }}"

- name: assign user {{ project_admin }} as project admin in {{ namespace }}
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/rolebinding.yml') | from_yaml }}"
  when: >
    project_admin is defined and
    project_admin is not none and
    project_admin|trim() != ""
