---

# create project

- name: "check existence of namespace {{ namespace }}"
  kubernetes.core.k8s_info:
    kind: Project
    api_version: project.openshift.io/v1
    name: "{{ namespace }}"
  register: r_project

- name: create project {{ namespace }}
  kubernetes.core.k8s:
    kind: Project
    api_version: project.openshift.io/v1
    name: "{{ namespace }}"
    state: present
    definition: "{{ lookup('template', 'templates/project.yml') | from_yaml }}"
  when:
    - r_project.resources | length == 0

- name: assign user {{ project_admin }} as project admin in {{ namespace }}
  kubernetes.core.k8s:
    kind: RoleBinding
    name: "{{ project_admin }}-admin"
    api_version: rbac.authorization.k8s.io/v1
    state: present
    definition: "{{ lookup('template', 'templates/rolebinding.yml') | from_yaml }}"
  when: >
    project_admin is defined and
    project_admin is not none and
    project_admin|trim() != "" and
    r_project.resources | length == 0
