---

##################      install         ########################
# 1)  AMQ Streams Operator
- set_fact:
    namespace: "{{ project_name }}"
    work_dir_name: "amq-streams-operator"
- include_role:
    name: ../roles/amq_streams_operator
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"

# 2) AMQ Streams Kafka cluster
- set_fact:
    namespace: "{{ project_name }}"
    work_dir_name: "kafka_cluster"
- include_role:
    name: ../roles/kafka_cluster
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"

# 5) Kafdrop
- set_fact:
    namespace: "{{ project_name }}"
    work_dir_name: "kafkadrop"
- include_role:
    name: ../roles/kafdrop
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"

###################################################################



##################      uninstall         ########################
# 1) Kafdrop
- set_fact:
    namespace: "{{ project_name }}"
    work_dir_name: "kafkadrop"
- include_role:
    name: ../roles/kafdrop
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"



# 4) AMQ Streams Kafka cluster
- set_fact:
    namespace: "{{ project_name }}"
    work_dir_name: "kafka_cluster"
- include_role:
    name: ../roles/kafka_cluster
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"

# 5) amq-streams-operator
- set_fact:
    namespace: "{{ project_name }}"
    work_dir_name: "amq-streams-operator"
- include_role:
    name: ../roles/amq_streams_operator
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
