---

- set_fact:
    namespace: "{{ project_name }}"
    resources_dir: "{{ resources_base_dir }}/knative"
    work_dir_name: knative
- include_role:
    name: ../roles/knative
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"
- include_role:
    name: ../roles/knative
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
