---

- name: "delete amq streams operator in {{ namespace_amq_streams_operator }} namespace"
  import_role:
    name: ../roles/operator_olm
    tasks_from: uninstall
  vars:
    operator_name: amq-streams-operator
    subscription_namespace: "{{ namespace_amq_streams_operator }}"
    subscription_name: "{{ amq_streams_operator_subscription_name }}"
    csv_prefix: "{{ amq_streams_operator_csv_prefix }}"
  when: undeploy_amq_operator is defined and undeploy_amq_operator == "true"

