---

- name: "create imagestream in the {{ namespace }} project"
  k8s:
    state: present
    kind: ImageStream
    definition: "{{ lookup('template', 'templates/' + binary_imagestream_template) | from_yaml }}"
    namespace: "{{ namespace }}"

- set_fact:
    application_image_tag: "{{ service_image_tag }}"

- name: "deploy {{ application_name }} application"
  k8s:
    state: present
    kind: DeploymentConfig
    definition: "{{ lookup('template', 'templates/' + application_template ) | from_yaml }}"
    namespace: "{{ namespace }}"

- name: "wait until {{ application_name }} application is up and running"
  shell: "{{ openshift_cli }} get dc {{ application_name }} -o template --template={{ json_template }} -n {{ namespace }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 10
  delay: 30
  changed_when: false
