---

- name: delete debezium connector
  k8s:
    state: absent
    name: "{{ kafka_debezium_name }}"
    namespace: "{{ namespace_kafka_cluster }}"
    kind: kafkaConnector
  ignore_errors: yes

- name: delete route
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: route
  ignore_errors: yes

- name: delete service
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: service
  ignore_errors: yes


- name: delete deployment config {{ application_name }}
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: DeploymentConfig
  ignore_errors: yes

- name: delete imagestream in the {{ namespace }} project
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream
  ignore_errors: yes

- name: "delete configmap {{ application_configmap }}"
  k8s:
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap
  ignore_errors: yes

- name: delete postgresql dc {{ psql_app_name  }}
  k8s:
    state: absent
    name: "{{ psql_app_name  }}"
    namespace: "{{ namespace }}"
    kind: DeploymentConfig
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"
  ignore_errors: yes

- name: delete postgresql service
  k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    kind: service
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"
  ignore_errors: yes

- name: delete postgresql pvc
  k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    kind: pvc
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"
  ignore_errors: yes

- name: delete postgresql secret
  k8s:
    namespace: "{{ namespace }}"
    name: "{{ psql_app_name }}"
    state: absent
    kind: secret
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"
  ignore_errors: yes

- name: delete postgresql init configmap
  k8s:
    state: absent
    name: "{{ postgresql_init_configmap }}"
    namespace: "{{ namespace }}"
    kind: ConfigMap
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"
  ignore_errors: yes

- name: delete {{ postgresql_service_account }} service account
  k8s:
    state: absent
    name: "{{ postgresql_service_account }}"
    namespace: "{{ namespace }}"
    kind: ServiceAccount
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"
  ignore_errors: yes
