---

- name: delete debezium connector
  kubernetes.core.k8s:
    state: absent
    name: "{{ kafka_debezium_name }}"
    namespace: "{{ namespace_kafka_cluster }}"
    kind: KafkaConnector
    api_version: kafka.strimzi.io/v1beta2

- name: delete route
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: Route
    api_version: route.openshift.io/v1

- name: delete service
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: Service


- name: delete deployment config {{ application_name }}
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: DeploymentConfig
    api_version: apps.openshift.io/v1

- name: delete imagestream in the {{ namespace }} project
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: ImageStream
    api_version: image.openshift.io/v1

- name: "delete configmap {{ application_configmap }}"
  kubernetes.core.k8s:
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: ConfigMap

- name: delete postgresql dc {{ psql_app_name  }}
  kubernetes.core.k8s:
    state: absent
    name: "{{ psql_app_name  }}"
    namespace: "{{ namespace }}"
    kind: DeploymentConfig
    api_version: apps.openshift.io/v1
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"

- name: delete postgresql service
  kubernetes.core.k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    kind: Service
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"

- name: delete postgresql pvc
  kubernetes.core.k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    kind: PersistentVolumeClaim
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"

- name: delete postgresql secret
  kubernetes.core.k8s:
    namespace: "{{ namespace }}"
    name: "{{ psql_app_name }}"
    state: absent
    kind: Secret
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"

- name: delete postgresql init configmap
  kubernetes.core.k8s:
    state: absent
    name: "{{ postgresql_init_configmap }}"
    namespace: "{{ namespace }}"
    kind: ConfigMap
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"

- name: delete {{ postgresql_service_account }} service account
  kubernetes.core.k8s:
    state: absent
    name: "{{ postgresql_service_account }}"
    namespace: "{{ namespace }}"
    kind: ServiceAccount
  when: undeploy_fhir_db is defined and undeploy_fhir_db|trim() == "true"
