---

namespace_amq_streams_operator: "openshift-operators"
namespace_kafka_cluster: "{{ project_name }}"

kafka_cluster: kafka-cluster

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
