---

- name: "remove knativeserving"
  kubernetes.core.k8s:
    state: absent
    kind: KnativeServing
    namespace: "{{ namespace_knativeserving }}"
    name: knative-ks
    api_version: operator.knative.dev/v1alpha1
  when: undeploy_knative is defined and undeploy_knative == "true"

- name: "delete serverless operator in {{ namespace_serverless_operator }} namespace"
  import_role:
    name: ../roles/operator_olm
    tasks_from: uninstall
  vars:
    operator_name: serverless-operator
    subscription_namespace: "{{ namespace_serverless_operator }}"
    subscription_name: "{{ serverless_operator_subscription_name }}"
    csv_prefix: "{{ serverless_operator_csv_prefix }}"
  when: undeploy_knative is defined and undeploy_knative == "true"

- name: "Delete {{ namespace_knativeserving }} project"
  kubernetes.core.k8s:
    state: absent
    kind: Project
    name: "{{ namespace_knativeserving }}"
    api_version: project.openshift.io/v1
  when: undeploy_knative is defined and undeploy_knative == "true"

