---

- name: "delete route {{ application_name }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: route.openshift.io/v1
    kind: Route

- name: "delete service {{ application_name }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: Service

- name: "delete DeploymentConfig {{ application_name }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig

- name: delete {{ application_name }} service account
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: ServiceAccount

