---

- name: Deploy all amq-streams artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml

  tasks:
    - include: tasks/amq-streams.yml
