---

- name: Deploy all sepsisdetection artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml
    - group_vars/smilecdr_server.yml
    - group_vars/sepsisdetection_rhpam.yml
  vars:
    ACTION: install

  tasks:
  - include: tasks/amq-streams.yml
  - include: tasks/knative.yml
  - include: tasks/sso.yml
  - include: tasks/smilecdr-server.yml
  - include: tasks/sepsisdetection-sse.yml
  - include: tasks/sepsisdetection-risk.yml
  - include: tasks/sepsisdetection-ml.yml
  - include: tasks/sepsisdetection-rhpam.yml
  - include: tasks/dashbuilder.yml
  - include: tasks/sepsisdetection-ui.yml
