---

- name: Deploy Knative
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml

  tasks:
    - include: tasks/knative.yml
