---

- name: Deploy SepsisDetection RHPAM
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml
    - group_vars/smilecdr_server.yml
    - group_vars/sepsisdetection_rhpam.yml

  tasks:
    - include: tasks/sepsisdetection-rhpam.yml
