---

- name: Deploy SmileCDR related artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml
    - group_vars/smilecdr_server.yml

  tasks:
    - include: tasks/smilecdr_server
