= kafka-connect-debezium-postgresql

== Purpose
There is already a Debezium connector image (https://hub.docker.com/r/debezium/connect   or  https://quay.io/repository/debezium/connect) with the ability for Change Data Capture of a PostgreSQL database.
This Debezium link:https://debezium.io/documentation/reference/stable/tutorial.html[tutorial] provides a good example of how to use it.

This connector includes libraries for all databases (ie:  db2, mongodb, mysql, oracle, postgresql, sqlserver and vitess).
For the purpose of the HIMSS 2021 demo, only the libraries to capture change events from PostgreSQL are needed.
Thus, for the purpose of utilizing a slimmer container image, this image is derived from `registry.redhat.io/amq7/amq-streams-kafka-26-rhel7:1.7.0` and augmented with Debezium PostgreSQL connector bits only.

== Usage
Execute the following to build this image

. Download the `1.5.0.Final` version of the debezium PostgreSQL connector.
+
-----
$ wget https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.5.0.Final/debezium-connector-postgres-1.5.0.Final-plugin.tar.gz 
-----

. Extract contents into the `contrib` directory.

. Build the image:
+
-----
$ buildah bud -f Dockerfile -t quay.io/redhat_naps_da/strimzi-debezium-postgresql:1.7.0-1.5.0.Final .
-----

. Push the image:
+
-----
$ podman push quay.io/redhat_naps_da/strimzi-debezium-postgresql:1.7.0-1.5.0.Final
-----

