apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ application_name }}
spec:
  host: {{ route_hostname }}
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ application_name }}
  wildcardPolicy: None
