---

namespace_amq_streams_operator: "{{ project_name }}"
namespace_kafka_cluster: "{{ project_name }}"

kafka_cluster: kafka-cluster

kafka_connect: kafka-connect

kafka_topics: >
  [{"name": "{{ kafka_connect }}-offsets", "partitions": "25", "replicas": "3", "config": '{"cleanup.policy": "compact"}'},
   {"name": "{{ kafka_connect }}-configs", "partitions": "1", "replicas": "3", "config": '{"cleanup.policy": "compact"}'},
   {"name": "{{ kafka_connect }}-status", "partitions": "5", "replicas": "3", "config": '{"cleanup.policy": "compact"}'}]

kafka_bootstrap_service: "kafka-cluster-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"

kafka_connect_image: quay.io/redhat_naps_da/strimzi-debezium-postgresql:1.7.0-1.5.0.Final
