---

- name: "Download {{ binary_imagestream_template_url }}"
  get_url:
    url: "{{ binary_imagestream_template_url }}"
    dest: "{{ work_dir }}/{{ binary_imagestream_template}}"
    force: yes

- name: create imagestream {{ application_name }} in the {{ namespace }} project
  kubernetes.core.k8s:
    state: present
    kind: ImageStream
    definition: "{{ lookup('template', work_dir + '/' + binary_imagestream_template) | from_yaml }}"
    namespace: "{{ namespace }}"

- name: "Download {{ application_template_url }}"
  get_url:
    url: "{{ application_template_url }}"
    dest: "{{ work_dir }}/{{ application_template}}"
    force: yes

- name: deploy {{ application_name }} application
  kubernetes.core.k8s:
    state: present
    kind: DeploymentConfig
    definition: "{{ lookup('template', work_dir + '/' + application_template ) | from_yaml }}"
    namespace: "{{ namespace }}"
