---

- name: "delete service.serving.knative.dev {{ application_name }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: serving.knative.dev/v1
    kind: Service

- name: delete {{ application_name }} service account
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: ServiceAccount

- name: "delete routes.serving.knative.dev {{ application_name }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: serving.knative.dev/v1
    kind: Route

- name: "delete ingresses.networking.internal.knative.dev {{ application_name }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: networking.internal.knative.dev/v1alpha1
    kind: Ingress

