---

- name: delete route
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: route.openshift.io/v1
    kind: Route

- name: delete service
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: Service

- name: delete deployment config
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig

- name: delete imagestream in the {{ namespace }} project
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    api_version: image.openshift.io/v1
    kind: ImageStream

- name: "delete configmap {{ application_configmap }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: delete postgresql dc
  k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig
  when: undeploy_psql_bpm is defined and undeploy_psql_bpm == "true"

- name: delete postgresql service
  k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    kind: Service
  when: undeploy_psql_bpm is defined and undeploy_psql_bpm == "true"

- name: "delete {{ psql_app_name }} pvc"
  k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    kind: PersistentVolumeClaim
  when: undeploy_psql_bpm is defined and undeploy_psql_bpm == "true"

- name: delete postgresql secret
  k8s:
    state: absent
    name: "{{ psql_app_name }}"
    namespace: "{{ namespace }}"
    kind: Secret
  when: undeploy_psql_bpm is defined and undeploy_psql_bpm == "true"

- name: delete postgresql init configmap
  k8s:
    state: absent
    name: "{{ postgresql_init_configmap }}"
    namespace: "{{ namespace }}"
    kind: ConfigMap
  when: undeploy_psql_bpm is defined and undeploy_psql_bpm == "true"

- name: delete {{ postgresql_service_account }} service account
  k8s:
    state: absent
    name: "{{ postgresql_service_account }}"
    namespace: "{{ namespace }}"
    kind: ServiceAccount
  when: undeploy_psql_bpm is defined and undeploy_psql_bpm == "true"
