apiVersion: v1
kind: Service
metadata:
  labels:
    app: sepsisdetection-risk
    monitoring: prometheus
    expose: "true"
  name: sepsisdetection-risk
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    group: sepsis 
    app: sepsisdetection-risk
  sessionAffinity: None
  type: ClusterIP
